languageCode = "en-us"
title = "Massively"
baseURL = "http://localhost:1313"
theme = "hugo-theme-massively"
googleanalytics = ""
disqusShortname = ""

# [params]
  # set below parameter to define a favicon
  # favicon = "favicon.ico"

# Below parameters can be set to override default post settings
# [params.posts]
#     foldername = "post"
#     pagesize = "6"
#     featuredpost = "true"

[languages]
[languages.en]
  languageName = "English"
  title = "Practical English"
[languages.th]
  languageName = "ไทย"
  title = "ภาษาอังกฤษประยุกต์"
  
